"""Migration take 2

Revision ID: 7c6f3e4f35de
Revises: 4fadcfbfd8cf
Create Date: 2024-12-07 12:13:06.592659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c6f3e4f35de'
down_revision: Union[str, None] = '4fadcfbfd8cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
